### ISSUE TITLE
Redesign ranking won/lost statistic

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#107]
**Todo:**
- [x] Extend player model by wons / lost fields and update it after match complete.
- [x] Update players in db by new fields actual values.
- [x] Make changes in front-end component.
