### ISSUE TITLE
Update front-end

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#145]
**Todo:**
- [ ] Update to newest Angular version
- [ ] Replace deprecated _HttpModule_
- [ ] Replace deprecated method NgbModule.forRoot()
- [ ] Update bootstrap version (_bootstrap_ and _ng-bootstrap_)
