### ISSUE TITLE
T&C component

### ISSUE THREAD

**Issue by tomek199** [tomek199/elo-rating#64]
Add a component with league's terms and conditions. T&C should be stored in database and it should be editable. 

**Todo:**

- [ ] List of terms and conditions
- [ ] Add new list item
- [ ] Edit list item
- [ ] Delete list item
- [ ] Link to component in main navbar
